name: Build Application

runs:
  using: composite

  steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Set up Python ^3.12
    uses: actions/setup-python@v5
    with:
      python-version: '^3.12'

  - name: Install poetry
    uses: snok/install-poetry@v1
    with:
      virtualenvs-in-project: true

  - name: Install dependencies using poetry
    run: poetry install
    shell: bash

  - name: Run make install
    run: poetry run make install
    shell: bash
