# GitHub Actions workflow

name: App Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install poetry
      run: |
        (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -
        $env:PATH += ";C:\Users\runneradmin\AppData\Roaming\Python\Scripts"
      
    - name: Install dependencies using poetry
      run: C:\Users\runneradmin\AppData\Roaming\Python\Scripts\poetry run make install
    
    - name: Lint with flake8
      run: C:\Users\runneradmin\AppData\Roaming\Python\Scripts\poetry run make check
